from psonic import *
import random

F6 = 89
Ds6 = 87
Cs6 = 85
As6 = 94

use_synth(PIANO)

def group_zero():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                   play(As2);                          play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                    play(F6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                                   play(Ds6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                       play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                   play(F2);                                       play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Ds6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                               play(F3);               play(F5)
    pass;       sleep(0.13)

def group_one():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                                                       play(Gs5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                       play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                   play(As2)
    pass;                                                       play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(F6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Ds6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                       play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                   play(F2)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                   play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)

def group_two():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                                                                   play(Ds6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                                                                    play(Cs6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                               play(F3);                            play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                       play(Gs5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                                   play(C6)
    pass;       sleep(0.13)
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                                                       play(As5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;                   play(As6);                          play(C5)
    pass;                                                       play(D5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(As3);              play(Ds5)
    pass;                                                       play(Gs5)
    pass;       sleep(0.13)
    pass;                   play(As2);                          play(F5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;                   play(As2)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(C4)
    pass;       sleep(0.13)
    pass;                               play(As3)
    pass;       sleep(0.13)
    pass;                                           play(C4)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(Cs4)
    pass;       sleep(0.13)
    pass;                   play(Cs2)
    pass;       sleep(0.13)
    pass;                               play(As3);  play(Ds4)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(Fs4);  play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)

def group_three():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                               play(As3);              play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(C5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(Gs5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);              play(F5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(C5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(As4);  play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);                          play(Cs5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3);              play(Gs5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;                   play(Fs2);                           play(F5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);              play(Ds4)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(Cs4)
    pass;       sleep(0.13)
    pass;                                           play(Ds4)
    pass;       sleep(0.13)

def group_four():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                   play(Fs2);              play(F4)
    pass;       sleep(0.13)
    pass;                   play(Fs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(Fs4)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);              play(Gs4);  play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(As5);  play(F5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(F2);                           play(Fs5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;                   play(F2)       
    pass;       sleep(0.13)
    pass;                               play(F3)
    pass;       sleep(0.13)
    pass;                   play(F2);                           play(Gs5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                                                       play(F3)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(F2);               play(As4);  play(F5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(F3)
    pass;       sleep(0.13)
    pass;                                           play(As4);  play(Fs5)
    pass;       sleep(0.13)
    pass;                   play(F2)
    pass;       sleep(0.13)
    pass;                   play(F2)
    pass;       sleep(0.13)
    pass;                               play(F3)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(As2);                          play(C5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)

def group_five():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                               play(As3);              play(Ds5)
    pass;                                                       play(Gs5)
    pass;       sleep(0.13)
    pass;                   play(As2);                          play(Cs5)
    pass;                                                        play(F5)
    pass;       sleep(0.13)
    pass;                   play(As2)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(C4)
    pass;       sleep(0.13)
    pass;                               play(As3)
    pass;       sleep(0.13)
    pass;                                           play(C4)       
    pass;       sleep(0.13)
    pass;                   play(As2);              play(Cs4)
    pass;       sleep(0.13)
    pass;                   play(As2)       
    pass;       sleep(0.13)
    pass;                               play(As3);  play(Ds4)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(F4);   play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(As3);              play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(Ds5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(Gs5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);              play(Cs5)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3)
    pass;       sleep(0.13)
    pass;       sleep(0.13)

def group_six():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                   play(Gs2);                          play(C5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;                   play(Gs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(As4);  play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);                          play(Ds5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3);              play(Gs5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;                   play(Fs2);                          play(F5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);              play(Ds4)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(Cs4)
    pass;       sleep(0.13)
    pass;                                           play(Ds4)
    pass;       sleep(0.13)
    pass;                   play(Fs2);              play(F4)
    pass;       sleep(0.13)
    pass;                   play(Fs2)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(Fs4)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Fs2);              play(Gs4);  play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(Gs3);  play(As4);  play(F5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(F2);                           play(Fs5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;                   play(F2)
    pass;       sleep(0.13)
    pass;                               play(F3)
    pass;       sleep(0.13)
    pass;                   play(F2);                           play(Gs5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(F2)
    pass;       sleep(0.13)

def group_seven():
    # pass      # sleep     # oct2      # oct3      # oct4      # oct5      # oct6
    pass;                               play(F3)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(F2);               play(A4)
    pass;       sleep(0.13)
    pass;                               play(F3);               play(A5)       
    pass;                                                       play(F5)       
    pass;       sleep(0.13)
    pass;                   play(G2);               play(As4)
    pass;       sleep(0.13)
    pass;                               play(G3);               play(G5)       
    pass;                                                       play(As5)       
    pass;       sleep(0.13)
    pass;                   play(A2);                           play(C5)
    pass;       sleep(0.13)
    pass;                               play(A3);               play(A5);   play(C6)
    pass;       sleep(0.13)
    pass;                               play(C3);               play(Cs5)
    pass;       sleep(0.13)
    pass;                                           play(C4);  play(As5);  play(Cs6)
    pass;       sleep(0.13)
    pass;                   play(As2);                          play(C5)
    pass;                                                       play(Ds5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(As2);              play(As4);  play(Cs5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                               play(As3)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(Ds5)
    pass;                                                       play(C5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2);              play(As4);  play(Cs5)
    pass;       sleep(0.13)
    pass;                                                       play(F5)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;       sleep(0.13)
    pass;                   play(Gs2);                          play(As5)
    pass;                                                       play(Cs5)
    pass;       sleep(0.13)
    pass;                               play(Gs3)
    pass;       sleep(0.13)

group_zero()
group_one()
group_two()
group_three()
group_four()
group_five()
group_six()
group_seven()
